apiVersion: v1
kind: Service
metadata:
  name: app
spec:
 template:
    spec:
      containers:
        - name: app
          image: {{.Values.imageRegistry}}/app:{{.Values.dockerTag}}
          imagePullPolicy: {{.Values.pullPolicy}}
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
 template:
    spec:
      containers:
        - name: app
          image: {{.Values.imageRegistry}}/app:{{.Values.dockerTag}}
          imagePullPolicy: {{.Values.pullPolicy}}
---
apiVersion: v1
kind: Service
metadata:
  name: configurer
spec:
 template:
    spec:
      containers:
        - name: configurer
          image: {{.Values.imageRegistry}}/configurer:{{.Values.dockerTag}}
          imagePullPolicy: {{.Values.pullPolicy}}
