apiVersion: v1
kind: Service
metadata:
  name: alpha-global-app
spec:
  template:
    spec:
      containers:
        - name: alpha-global-app
          image: {{.Values.imageRegistry}}/alpha-global-app:{{.Values.dockerTag}}
          imagePullPolicy: {{.Values.pullPolicy}}
---
apiVersion: v1
kind: Service
metadata:
  name: vendor-db
spec:
  template:
    spec:
      containers:
        - name: vendor-db
          image: {{.Values.imageRegistry}}/vendor-db:{{.Values.dockerTag}}
          imagePullPolicy: {{.Values.pullPolicy}}
---
apiVersion: v1
kind: Service
metadata:
  name: vendor-configurer
spec:
  template:
    spec:
      initContainers:
        - name: alpha-market-config
          image: {{.Values.imageRegistry}}/alpha-market-config:{{.Values.dockerTag}}
          imagePullPolicy: {{.Values.pullPolicy}}
      containers:
        - name: vendor-configurer
          image: {{.Values.imageRegistry}}/vendor-configurer:{{.Values.dockerTag}}
          imagePullPolicy: {{.Values.pullPolicy}}
